### ISSUE TITLE
Graceful ignore of unknown strings

### ISSUE THREAD

**Issue by danielsparing** [IBMPredictiveAnalytics/Get_Coordinates_Esri#1]
Hi,

Currently when I work with this node and there is a string in the list for which ESRI returns no coordinates, my whole stream fails.

The inner function of coordinate assignment should be modified as the following:

```
function(x) {
    if (length(x$locations)) {
        lat <- x$locations[[1]]$feature$geometry$x
        lng <- x$locations[[1]]$feature$geometry$y
    } else {
        lat <- NA
        lng <- NA
    }
    return(c(lat,lng))
  }
```

**Comment by gfilla** [comment]
Hi-

Thank you for letting us know and for providing the code.  I tested this and it worked when I passed a bad string.  CFE and Source code have been updated with your code.
